// Code generated by protoc-gen-go.
// source: Messages.proto
// DO NOT EDIT!

/*
Package org_rpfl_transport_protobuf is a generated protocol buffer package.

It is generated from these files:
	Messages.proto

It has these top-level messages:
	Request
	Response
	ResponseEntry
*/
package org_rpfl_transport_protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type VerificationStrength int32

const (
	VerificationStrength_notfound   VerificationStrength = 1
	VerificationStrength_downloaded VerificationStrength = 2
	VerificationStrength_recompiled VerificationStrength = 3
)

var VerificationStrength_name = map[int32]string{
	1: "notfound",
	2: "downloaded",
	3: "recompiled",
}
var VerificationStrength_value = map[string]int32{
	"notfound":   1,
	"downloaded": 2,
	"recompiled": 3,
}

func (x VerificationStrength) Enum() *VerificationStrength {
	p := new(VerificationStrength)
	*p = x
	return p
}
func (x VerificationStrength) String() string {
	return proto.EnumName(VerificationStrength_name, int32(x))
}
func (x *VerificationStrength) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VerificationStrength_value, data, "VerificationStrength")
	if err != nil {
		return err
	}
	*x = VerificationStrength(value)
	return nil
}

type Request struct {
	Resources        []string `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Response struct {
	Entries          []*ResponseEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetEntries() []*ResponseEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ResponseEntry struct {
	Url                  *string               `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Hash                 []byte                `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
	VerificationStrength *VerificationStrength `protobuf:"varint,3,req,name=verificationStrength,enum=org.rpfl.transport.protobuf.VerificationStrength" json:"verificationStrength,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *ResponseEntry) Reset()         { *m = ResponseEntry{} }
func (m *ResponseEntry) String() string { return proto.CompactTextString(m) }
func (*ResponseEntry) ProtoMessage()    {}

func (m *ResponseEntry) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ResponseEntry) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ResponseEntry) GetVerificationStrength() VerificationStrength {
	if m != nil && m.VerificationStrength != nil {
		return *m.VerificationStrength
	}
	return VerificationStrength_notfound
}

func init() {
	proto.RegisterEnum("org.rpfl.transport.protobuf.VerificationStrength", VerificationStrength_name, VerificationStrength_value)
}
