// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.rpfl.transport.protobuf;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.rpfl.transport.protobuf.VerificationStrength}
   */
  public enum VerificationStrength
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>notfound = 1;</code>
     */
    notfound(0, 1),
    /**
     * <code>downloaded = 2;</code>
     */
    downloaded(1, 2),
    /**
     * <code>recompiled = 3;</code>
     */
    recompiled(2, 3),
    ;

    /**
     * <code>notfound = 1;</code>
     */
    public static final int notfound_VALUE = 1;
    /**
     * <code>downloaded = 2;</code>
     */
    public static final int downloaded_VALUE = 2;
    /**
     * <code>recompiled = 3;</code>
     */
    public static final int recompiled_VALUE = 3;


    public final int getNumber() { return value; }

    public static VerificationStrength valueOf(int value) {
      switch (value) {
        case 1: return notfound;
        case 2: return downloaded;
        case 3: return recompiled;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VerificationStrength>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<VerificationStrength>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VerificationStrength>() {
            public VerificationStrength findValueByNumber(int number) {
              return VerificationStrength.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.rpfl.transport.protobuf.Messages.getDescriptor().getEnumTypes().get(0);
    }

    private static final VerificationStrength[] VALUES = values();

    public static VerificationStrength valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private VerificationStrength(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.rpfl.transport.protobuf.VerificationStrength)
  }

  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string resources = 1;
    /**
     * <code>repeated string resources = 1;</code>
     */
    java.util.List<java.lang.String>
    getResourcesList();
    /**
     * <code>repeated string resources = 1;</code>
     */
    int getResourcesCount();
    /**
     * <code>repeated string resources = 1;</code>
     */
    java.lang.String getResources(int index);
    /**
     * <code>repeated string resources = 1;</code>
     */
    com.google.protobuf.ByteString
        getResourcesBytes(int index);
  }
  /**
   * Protobuf type {@code org.rpfl.transport.protobuf.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                resources_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              resources_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          resources_ = new com.google.protobuf.UnmodifiableLazyStringList(resources_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rpfl.transport.protobuf.Messages.Request.class, org.rpfl.transport.protobuf.Messages.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    // repeated string resources = 1;
    public static final int RESOURCES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList resources_;
    /**
     * <code>repeated string resources = 1;</code>
     */
    public java.util.List<java.lang.String>
        getResourcesList() {
      return resources_;
    }
    /**
     * <code>repeated string resources = 1;</code>
     */
    public int getResourcesCount() {
      return resources_.size();
    }
    /**
     * <code>repeated string resources = 1;</code>
     */
    public java.lang.String getResources(int index) {
      return resources_.get(index);
    }
    /**
     * <code>repeated string resources = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourcesBytes(int index) {
      return resources_.getByteString(index);
    }

    private void initFields() {
      resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < resources_.size(); i++) {
        output.writeBytes(1, resources_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < resources_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(resources_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getResourcesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rpfl.transport.protobuf.Messages.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.rpfl.transport.protobuf.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rpfl.transport.protobuf.Messages.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rpfl.transport.protobuf.Messages.Request.class, org.rpfl.transport.protobuf.Messages.Request.Builder.class);
      }

      // Construct using org.rpfl.transport.protobuf.Messages.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Request_descriptor;
      }

      public org.rpfl.transport.protobuf.Messages.Request getDefaultInstanceForType() {
        return org.rpfl.transport.protobuf.Messages.Request.getDefaultInstance();
      }

      public org.rpfl.transport.protobuf.Messages.Request build() {
        org.rpfl.transport.protobuf.Messages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rpfl.transport.protobuf.Messages.Request buildPartial() {
        org.rpfl.transport.protobuf.Messages.Request result = new org.rpfl.transport.protobuf.Messages.Request(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          resources_ = new com.google.protobuf.UnmodifiableLazyStringList(
              resources_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resources_ = resources_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rpfl.transport.protobuf.Messages.Request) {
          return mergeFrom((org.rpfl.transport.protobuf.Messages.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rpfl.transport.protobuf.Messages.Request other) {
        if (other == org.rpfl.transport.protobuf.Messages.Request.getDefaultInstance()) return this;
        if (!other.resources_.isEmpty()) {
          if (resources_.isEmpty()) {
            resources_ = other.resources_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResourcesIsMutable();
            resources_.addAll(other.resources_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rpfl.transport.protobuf.Messages.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rpfl.transport.protobuf.Messages.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string resources = 1;
      private com.google.protobuf.LazyStringList resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureResourcesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          resources_ = new com.google.protobuf.LazyStringArrayList(resources_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public java.util.List<java.lang.String>
          getResourcesList() {
        return java.util.Collections.unmodifiableList(resources_);
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public int getResourcesCount() {
        return resources_.size();
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public java.lang.String getResources(int index) {
        return resources_.get(index);
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResourcesBytes(int index) {
        return resources_.getByteString(index);
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public Builder setResources(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public Builder addResources(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public Builder addAllResources(
          java.lang.Iterable<java.lang.String> values) {
        ensureResourcesIsMutable();
        super.addAll(values, resources_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public Builder clearResources() {
        resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string resources = 1;</code>
       */
      public Builder addResourcesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.rpfl.transport.protobuf.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.rpfl.transport.protobuf.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry> 
        getEntriesList();
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    org.rpfl.transport.protobuf.Messages.ResponseEntry getEntries(int index);
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    java.util.List<? extends org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.rpfl.transport.protobuf.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entries_ = new java.util.ArrayList<org.rpfl.transport.protobuf.Messages.ResponseEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entries_.add(input.readMessage(org.rpfl.transport.protobuf.Messages.ResponseEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rpfl.transport.protobuf.Messages.Response.class, org.rpfl.transport.protobuf.Messages.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    // repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;
    public static final int ENTRIES_FIELD_NUMBER = 1;
    private java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry> entries_;
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    public java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    public java.util.List<? extends org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    public org.rpfl.transport.protobuf.Messages.ResponseEntry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
     */
    public org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private void initFields() {
      entries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntriesCount(); i++) {
        if (!getEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rpfl.transport.protobuf.Messages.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.rpfl.transport.protobuf.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rpfl.transport.protobuf.Messages.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rpfl.transport.protobuf.Messages.Response.class, org.rpfl.transport.protobuf.Messages.Response.Builder.class);
      }

      // Construct using org.rpfl.transport.protobuf.Messages.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_Response_descriptor;
      }

      public org.rpfl.transport.protobuf.Messages.Response getDefaultInstanceForType() {
        return org.rpfl.transport.protobuf.Messages.Response.getDefaultInstance();
      }

      public org.rpfl.transport.protobuf.Messages.Response build() {
        org.rpfl.transport.protobuf.Messages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rpfl.transport.protobuf.Messages.Response buildPartial() {
        org.rpfl.transport.protobuf.Messages.Response result = new org.rpfl.transport.protobuf.Messages.Response(this);
        int from_bitField0_ = bitField0_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rpfl.transport.protobuf.Messages.Response) {
          return mergeFrom((org.rpfl.transport.protobuf.Messages.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rpfl.transport.protobuf.Messages.Response other) {
        if (other == org.rpfl.transport.protobuf.Messages.Response.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntriesCount(); i++) {
          if (!getEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rpfl.transport.protobuf.Messages.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rpfl.transport.protobuf.Messages.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;
      private java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = new java.util.ArrayList<org.rpfl.transport.protobuf.Messages.ResponseEntry>(entries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.rpfl.transport.protobuf.Messages.ResponseEntry, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder, org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public org.rpfl.transport.protobuf.Messages.ResponseEntry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder setEntries(
          int index, org.rpfl.transport.protobuf.Messages.ResponseEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder setEntries(
          int index, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder addEntries(org.rpfl.transport.protobuf.Messages.ResponseEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder addEntries(
          int index, org.rpfl.transport.protobuf.Messages.ResponseEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder addEntries(
          org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder addEntries(
          int index, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends org.rpfl.transport.protobuf.Messages.ResponseEntry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          super.addAll(values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public java.util.List<? extends org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            org.rpfl.transport.protobuf.Messages.ResponseEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, org.rpfl.transport.protobuf.Messages.ResponseEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .org.rpfl.transport.protobuf.ResponseEntry entries = 1;</code>
       */
      public java.util.List<org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.rpfl.transport.protobuf.Messages.ResponseEntry, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder, org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.rpfl.transport.protobuf.Messages.ResponseEntry, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder, org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.rpfl.transport.protobuf.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.rpfl.transport.protobuf.Response)
  }

  public interface ResponseEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string url = 1;
    /**
     * <code>required string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    // required bytes hash = 2;
    /**
     * <code>required bytes hash = 2;</code>
     */
    boolean hasHash();
    /**
     * <code>required bytes hash = 2;</code>
     */
    com.google.protobuf.ByteString getHash();

    // required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;
    /**
     * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
     */
    boolean hasVerificationStrength();
    /**
     * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
     */
    org.rpfl.transport.protobuf.Messages.VerificationStrength getVerificationStrength();
  }
  /**
   * Protobuf type {@code org.rpfl.transport.protobuf.ResponseEntry}
   */
  public static final class ResponseEntry extends
      com.google.protobuf.GeneratedMessage
      implements ResponseEntryOrBuilder {
    // Use ResponseEntry.newBuilder() to construct.
    private ResponseEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseEntry defaultInstance;
    public static ResponseEntry getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              url_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              hash_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.rpfl.transport.protobuf.Messages.VerificationStrength value = org.rpfl.transport.protobuf.Messages.VerificationStrength.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                verificationStrength_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_ResponseEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rpfl.transport.protobuf.Messages.ResponseEntry.class, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseEntry> PARSER =
        new com.google.protobuf.AbstractParser<ResponseEntry>() {
      public ResponseEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string url = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>required string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes hash = 2;
    public static final int HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>required bytes hash = 2;</code>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes hash = 2;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    // required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;
    public static final int VERIFICATIONSTRENGTH_FIELD_NUMBER = 3;
    private org.rpfl.transport.protobuf.Messages.VerificationStrength verificationStrength_;
    /**
     * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
     */
    public boolean hasVerificationStrength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
     */
    public org.rpfl.transport.protobuf.Messages.VerificationStrength getVerificationStrength() {
      return verificationStrength_;
    }

    private void initFields() {
      url_ = "";
      hash_ = com.google.protobuf.ByteString.EMPTY;
      verificationStrength_ = org.rpfl.transport.protobuf.Messages.VerificationStrength.notfound;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVerificationStrength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, verificationStrength_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, verificationStrength_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rpfl.transport.protobuf.Messages.ResponseEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rpfl.transport.protobuf.Messages.ResponseEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.rpfl.transport.protobuf.ResponseEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rpfl.transport.protobuf.Messages.ResponseEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_ResponseEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rpfl.transport.protobuf.Messages.ResponseEntry.class, org.rpfl.transport.protobuf.Messages.ResponseEntry.Builder.class);
      }

      // Construct using org.rpfl.transport.protobuf.Messages.ResponseEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        verificationStrength_ = org.rpfl.transport.protobuf.Messages.VerificationStrength.notfound;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rpfl.transport.protobuf.Messages.internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor;
      }

      public org.rpfl.transport.protobuf.Messages.ResponseEntry getDefaultInstanceForType() {
        return org.rpfl.transport.protobuf.Messages.ResponseEntry.getDefaultInstance();
      }

      public org.rpfl.transport.protobuf.Messages.ResponseEntry build() {
        org.rpfl.transport.protobuf.Messages.ResponseEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rpfl.transport.protobuf.Messages.ResponseEntry buildPartial() {
        org.rpfl.transport.protobuf.Messages.ResponseEntry result = new org.rpfl.transport.protobuf.Messages.ResponseEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.verificationStrength_ = verificationStrength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rpfl.transport.protobuf.Messages.ResponseEntry) {
          return mergeFrom((org.rpfl.transport.protobuf.Messages.ResponseEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rpfl.transport.protobuf.Messages.ResponseEntry other) {
        if (other == org.rpfl.transport.protobuf.Messages.ResponseEntry.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasVerificationStrength()) {
          setVerificationStrength(other.getVerificationStrength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasHash()) {
          
          return false;
        }
        if (!hasVerificationStrength()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rpfl.transport.protobuf.Messages.ResponseEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rpfl.transport.protobuf.Messages.ResponseEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string url = 1;
      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      // required bytes hash = 2;
      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes hash = 2;</code>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      // required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;
      private org.rpfl.transport.protobuf.Messages.VerificationStrength verificationStrength_ = org.rpfl.transport.protobuf.Messages.VerificationStrength.notfound;
      /**
       * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
       */
      public boolean hasVerificationStrength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
       */
      public org.rpfl.transport.protobuf.Messages.VerificationStrength getVerificationStrength() {
        return verificationStrength_;
      }
      /**
       * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
       */
      public Builder setVerificationStrength(org.rpfl.transport.protobuf.Messages.VerificationStrength value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        verificationStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.rpfl.transport.protobuf.VerificationStrength verificationStrength = 3;</code>
       */
      public Builder clearVerificationStrength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        verificationStrength_ = org.rpfl.transport.protobuf.Messages.VerificationStrength.notfound;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.rpfl.transport.protobuf.ResponseEntry)
    }

    static {
      defaultInstance = new ResponseEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.rpfl.transport.protobuf.ResponseEntry)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_rpfl_transport_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_rpfl_transport_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_rpfl_transport_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_rpfl_transport_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_rpfl_transport_protobuf_ResponseEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Messages.proto\022\033org.rpfl.transport.pro" +
      "tobuf\"\034\n\007Request\022\021\n\tresources\030\001 \003(\t\"G\n\010R" +
      "esponse\022;\n\007entries\030\001 \003(\0132*.org.rpfl.tran" +
      "sport.protobuf.ResponseEntry\"{\n\rResponse" +
      "Entry\022\013\n\003url\030\001 \002(\t\022\014\n\004hash\030\002 \002(\014\022O\n\024veri" +
      "ficationStrength\030\003 \002(\01621.org.rpfl.transp" +
      "ort.protobuf.VerificationStrength*D\n\024Ver" +
      "ificationStrength\022\014\n\010notfound\020\001\022\016\n\ndownl" +
      "oaded\020\002\022\016\n\nrecompiled\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_rpfl_transport_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_rpfl_transport_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_rpfl_transport_protobuf_Request_descriptor,
              new java.lang.String[] { "Resources", });
          internal_static_org_rpfl_transport_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_rpfl_transport_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_rpfl_transport_protobuf_Response_descriptor,
              new java.lang.String[] { "Entries", });
          internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_rpfl_transport_protobuf_ResponseEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_rpfl_transport_protobuf_ResponseEntry_descriptor,
              new java.lang.String[] { "Url", "Hash", "VerificationStrength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
